/**
 * HTML Reporter
 *
 * Generates a standalone HTML report from accessibility audit results.
 * The report is self-contained with embedded CSS and can be opened in any browser.
 */

import type { Reporter, ReportData, ReportOutput, ReporterOptions } from '../reporter';
import type { StrategyResult } from '../../screen-reader/navigation-strategy/browse-mode-strategies/navigation-strategy';
import {
    generateFilename,
    formatTimestamp,
    formatDuration,
    getSeverityColor,
    getAssessmentColor,
    getConfidenceColor,
    escapeHtml,
    truncate,
} from '../reporter';
import type { LlmFinding, LlmViolationEnhancement } from '../../llm/prompt-builder';

// =============================================================================
// HTML Reporter Options
// =============================================================================

export interface HtmlReporterOptions extends ReporterOptions {
    /** Theme: 'light' or 'dark' */
    theme?: 'light' | 'dark';

    /** Include collapsible sections */
    collapsible?: boolean;

    /** Include search/filter functionality */
    interactive?: boolean;

    /** Logo URL to include in header */
    logoUrl?: string;

    /** Custom CSS to inject */
    customCss?: string;
}

const DEFAULT_OPTIONS: Required<HtmlReporterOptions> = {
    includeTranscript: true,
    includeHtmlSnippets: true,
    title: 'Accessibility Audit Report',
    theme: 'light',
    collapsible: true,
    interactive: true,
    logoUrl: '',
    customCss: '',
};

// =============================================================================
// HTML Reporter Implementation
// =============================================================================

export class HtmlReporter implements Reporter {
    readonly name = 'html';

    async generate(data: ReportData, options?: HtmlReporterOptions): Promise<ReportOutput> {
        const opts = { ...DEFAULT_OPTIONS, ...options };
        const html = this.buildHtml(data, opts);

        return {
            format: 'html',
            content: html,
            filename: generateFilename('accessibility-report', 'html'),
            mimeType: 'text/html',
        };
    }

    private buildHtml(data: ReportData, opts: Required<HtmlReporterOptions>): string {
        return `<!DOCTYPE html>
<html lang="en" data-theme="${opts.theme}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapeHtml(opts.title)}</title>
    <style>${this.getStyles(opts)}</style>
</head>
<body>
    ${this.buildHeader(data, opts)}
    <main>
        ${this.buildSummary(data)}
        ${this.buildFindings(data)}
        ${this.buildEnhancements(data)}
        ${opts.includeTranscript ? this.buildTranscript(data) : ''}
        ${this.buildLimitations(data)}
    </main>
    ${this.buildFooter(data)}
    ${opts.interactive ? this.getScripts() : ''}
</body>
</html>`;
    }

    // -------------------------------------------------------------------------
    // Header & Footer
    // -------------------------------------------------------------------------

    private buildHeader(data: ReportData, opts: Required<HtmlReporterOptions>): string {
        const logo = opts.logoUrl ? `<img src="${escapeHtml(opts.logoUrl)}" alt="Logo" class="logo">` : '';

        return `
<header>
    <div class="header-content">
        ${logo}
        <div class="header-text">
            <h1>${escapeHtml(opts.title)}</h1>
            <p class="page-info">
                <strong>URL:</strong> <a href="${escapeHtml(data.page.url)}" target="_blank">${escapeHtml(data.page.url)}</a><br>
                <strong>Title:</strong> ${escapeHtml(data.page.title)}
            </p>
        </div>
    </div>
    <div class="meta-info">
        <span>Generated: ${formatTimestamp(data.meta.timestamp)}</span>
        ${data.meta.duration ? `<span>Duration: ${formatDuration(data.meta.duration)}</span>` : ''}
        ${data.meta.toolVersion ? `<span>Tool: v${escapeHtml(data.meta.toolVersion)}</span>` : ''}
    </div>
</header>`;
    }

    private buildFooter(data: ReportData): string {
        return `
<footer>
    <p>Generated by NVDA Accessibility Audit Tool</p>
    <p>Report ID: ${data.meta.timestamp}</p>
</footer>`;
    }

    // -------------------------------------------------------------------------
    // Summary Section
    // -------------------------------------------------------------------------

    private buildSummary(data: ReportData): string {
        const { summary } = data.analysis.analysis;
        const assessmentColor = getAssessmentColor(summary.overallAssessment);

        const findingsCount = data.analysis.analysis.findings.length;
        const enhancementsCount = data.analysis.enhancements.length;
        const violationsCount = data.violations.length;

        return `
<section class="summary" aria-labelledby="summary-heading">
    <h2 id="summary-heading">Summary</h2>
    
    <div class="assessment-badge" style="--badge-color: ${assessmentColor}">
        ${this.formatAssessment(summary.overallAssessment)}
    </div>

    <div class="stats-grid">
        <div class="stat-card">
            <span class="stat-value">${violationsCount}</span>
            <span class="stat-label">Rule Violations</span>
        </div>
        <div class="stat-card">
            <span class="stat-value">${findingsCount}</span>
            <span class="stat-label">LLM Findings</span>
        </div>
        <div class="stat-card">
            <span class="stat-value">${enhancementsCount}</span>
            <span class="stat-label">Enhancements</span>
        </div>
        <div class="stat-card">
            <span class="stat-value">${summary.totalSteps}</span>
            <span class="stat-label">Steps Analyzed</span>
        </div>
        <div class="stat-card">
            <span class="stat-value">${summary.stepsToMainContent ?? 'N/A'}</span>
            <span class="stat-label">Steps to Main</span>
        </div>
    </div>

    ${
        summary.majorConcerns.length > 0
            ? `
    <div class="major-concerns">
        <h3>Major Concerns</h3>
        <ul>
            ${summary.majorConcerns.map((c) => `<li>${escapeHtml(c)}</li>`).join('\n')}
        </ul>
    </div>
    `
            : ''
    }
</section>`;
    }

    private formatAssessment(assessment: string): string {
        return assessment;
    }

    // -------------------------------------------------------------------------
    // Findings Section
    // -------------------------------------------------------------------------

    private buildFindings(data: ReportData): string {
        const findings = data.analysis.analysis.findings;

        if (findings.length === 0) {
            return `
<section class="findings" aria-labelledby="findings-heading">
    <h2 id="findings-heading">LLM Findings</h2>
    <p class="no-items">No additional findings identified by LLM analysis.</p>
</section>`;
        }

        // Group by category
        const byCategory = this.groupBy(findings, (f) => f.category);

        return `
<section class="findings" aria-labelledby="findings-heading">
    <h2 id="findings-heading">LLM Findings <span class="count">(${findings.length})</span></h2>
    
    ${Object.entries(byCategory)
        .map(
            ([category, items]) => `
    <div class="category-group">
        <h3 class="category-heading">${this.formatCategory(category)} <span class="count">(${items.length})</span></h3>
        ${items.map((f) => this.buildFindingCard(f)).join('\n')}
    </div>
    `
        )
        .join('\n')}
</section>`;
    }

    private buildFindingCard(finding: LlmFinding): string {
        return `
<article class="finding-card">
    <p class="finding-issue">${escapeHtml(finding.issue)}</p>
    
    <div class="finding-meta">
        <span><strong>Category:</strong> ${escapeHtml(finding.category)}</span>
        <span><strong>Confidence:</strong> ${escapeHtml(finding.confidence)}</span>
        ${finding.classification ? `<span><strong>Classification:</strong> ${escapeHtml(finding.classification)}</span>` : ''}
        ${finding.relatedRuleId ? `<span><strong>Related rule:</strong> ${escapeHtml(finding.relatedRuleId)}</span>` : ''}
    </div>
    
    <div class="finding-details">
        <div class="detail-section">
            <h4>Impact</h4>
            <p>${escapeHtml(finding.impact)}</p>
        </div>
        
        <div class="detail-section">
            <h4>Evidence</h4>
            <ul class="evidence-list">
                ${finding.evidence.steps
                    .map(
                        (step) => `
                    <li>
                        <a href="#step-${escapeHtml(step.identifier)}" class="evidence-link">
                            <span class="evidence-ref">${escapeHtml(step.strategy)} [${step.stepIndex}]</span>
                        </a>
                        <code>${escapeHtml(step.spokenPhrase)}</code>
                    </li>
                `
                    )
                    .join('\n')}
            </ul>
            ${finding.evidence.pattern ? `<p class="pattern">${escapeHtml(finding.evidence.pattern)}</p>` : ''}
        </div>

        ${
            finding.semanticJustification
                ? `
        <div class="detail-section">
            <h4>Justification</h4>
            <p>${escapeHtml(finding.semanticJustification)}</p>
        </div>
        `
                : ''
        }
    </div>
    
    ${finding.requiresHumanReview ? '<p class="human-review">⚠ Requires human review</p>' : ''}
</article>`;
    }

    private formatCategory(category: string): string {
        return category;
    }

    // -------------------------------------------------------------------------
    // Enhancements Section
    // -------------------------------------------------------------------------

    private buildEnhancements(data: ReportData): string {
        const enhancements = data.analysis.enhancements;

        if (enhancements.length === 0) {
            return `
<section class="enhancements" aria-labelledby="enhancements-heading">
    <h2 id="enhancements-heading">Violation Enhancements</h2>
    <p class="no-items">No enhancements provided for existing violations.</p>
</section>`;
        }

        return `
<section class="enhancements" aria-labelledby="enhancements-heading">
    <h2 id="enhancements-heading">Violation Enhancements <span class="count">(${enhancements.length})</span></h2>
    
    <div class="enhancements-list">
        ${enhancements.map((e) => this.buildEnhancementCard(e, data)).join('\n')}
    </div>
</section>`;
    }

    private buildEnhancementCard(enhancement: LlmViolationEnhancement, data: ReportData): string {
        const confidenceColor = getConfidenceColor(enhancement.confidence);

        // Find original violation
        const violation = data.violations.find((v) => v.id === enhancement.violationId);

        return `
<article class="enhancement-card">
    <div class="enhancement-header">
        <span class="badge confidence" style="--badge-color: ${confidenceColor}">${enhancement.confidence}</span>
    </div>

    ${
        violation
            ? `
    <div class="original-violation-full">
        <div class="violation-meta">
            <strong>${escapeHtml(violation.ruleId)}</strong>
            <span class="wcag-badge">${escapeHtml(violation.wcag?.primary?.criterion ?? 'N/A')}</span>
            <span class="tool-badge">${escapeHtml(violation.tool ?? 'unknown')}</span>
            <span class="impact-badge">${escapeHtml(violation.impact)}</span>
        </div>
        <p class="violation-message">${escapeHtml(violation.message)}</p>
        ${
            violation.element?.selector
                ? `<p class="violation-selector"><code>${escapeHtml(violation.element.selector)}</code></p>`
                : ''
        }
        ${
            violation.element?.htmlSnippet
                ? `<pre class="violation-html"><code>${escapeHtml(truncate(violation.element.htmlSnippet, 500))}</code></pre>`
                : ''
        }
    </div>
    `
            : `<p class="no-items">Violation not found: ${escapeHtml(enhancement.violationId)}</p>`
    }

    ${
        enhancement.severityRationale
            ? `
    <div class="detail-section">
        <h4>Severity Rationale</h4>
        <p>${escapeHtml(enhancement.severityRationale)}</p>
    </div>
    `
            : ''
    }

    ${
        enhancement.userImpactDescription
            ? `
    <div class="detail-section">
        <h4>User Impact</h4>
        <p>${escapeHtml(enhancement.userImpactDescription)}</p>
    </div>
    `
            : ''
    }

    ${
        enhancement.remediationSuggestion
            ? `
    <div class="detail-section">
        <h4>Remediation</h4>
        <p>${escapeHtml(enhancement.remediationSuggestion)}</p>
    </div>
    `
            : ''
    }

    ${
        violation?.toolDetails
            ? `
    <details class="debug-details">
        <summary>Debug Info</summary>
        <pre class="debug-json"><code>${escapeHtml(JSON.stringify(violation.toolDetails, null, 2))}</code></pre>
    </details>
    `
            : ''
    }
</article>`;
    }

    // -------------------------------------------------------------------------
    // Transcript Section
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // Limitations Section
    // -------------------------------------------------------------------------

    private buildLimitations(data: ReportData): string {
        const limitations = data.analysis.analysis.limitations;

        if (limitations.length === 0) {
            return '';
        }

        return `
<section class="limitations" aria-labelledby="limitations-heading">
    <h2 id="limitations-heading">Analysis Limitations</h2>
    <p>The following aspects could not be determined from the transcript alone:</p>
    <ul>
        ${limitations.map((l) => `<li>${escapeHtml(l)}</li>`).join('\n')}
    </ul>
</section>`;
    }

    // -------------------------------------------------------------------------
    // Transcript Section
    // -------------------------------------------------------------------------

    private buildTranscript(data: ReportData): string {
        if (!data.strategyResults || data.strategyResults.length === 0) {
            return `
<section class="transcript" aria-labelledby="transcript-heading">
    <h2 id="transcript-heading">Screen Reader Transcript</h2>
    <p class="no-items">No transcript data available.</p>
</section>`;
        }

        const strategies = data.strategyResults.filter((s) => s.navigationSteps.length > 0);
        const totalSteps = strategies.reduce((sum, s) => sum + s.navigationSteps.length, 0);
        const cited = this.citedStepIdentifiers(data);

        const walkChips = strategies
            .map(
                (s) =>
                    `<button type="button" class="t-chip" data-walk="${escapeHtml(s.meta.name)}" aria-pressed="false" title="${escapeHtml(s.meta.description)}">${escapeHtml(s.meta.name)}<span class="t-chip-count">${s.navigationSteps.length}</span></button>`
            )
            .join('\n');

        const blocks = strategies
            .map((s) => {
                const lines = s.navigationSteps.map((step) => this.buildRow(step, s.meta.name, cited)).join('\n');
                return `
<div class="t-walk-block" data-walk="${escapeHtml(s.meta.name)}">
    <div class="t-walk-header" title="${escapeHtml(s.meta.description)}">
        <span class="t-walk-name">${escapeHtml(s.meta.name)}</span>
        <span class="t-walk-count">${s.navigationSteps.length} step${s.navigationSteps.length !== 1 ? 's' : ''}</span>
    </div>
    <div class="t-lines">
${lines}
    </div>
</div>`;
            })
            .join('\n');

        return `
<section class="transcript" aria-labelledby="transcript-heading">
    <h2 id="transcript-heading">Screen Reader Transcript <span class="count">${totalSteps} steps</span></h2>

    <div class="t-controls">
        <label class="t-search" for="transcript-filter">
            <span class="visually-hidden">Filter announcements</span>
            <input type="search" id="transcript-filter" placeholder="Filter announcements&hellip;" autocomplete="off">
        </label>
        <div class="t-chips" role="group" aria-label="Filter by navigation walk">
            <button type="button" class="t-chip is-active" data-walk="all" aria-pressed="true">All</button>
            ${walkChips}
        </div>
        <p class="t-status" role="status" aria-live="polite"></p>
    </div>

    <div class="t-body">
${blocks}
    </div>
</section>`;
    }

    /**
     * Step identifiers the analysis cites as evidence.
     *
     * The findings section links into the transcript; this lets the transcript
     * point back, so a reader scanning it can see which steps mattered.
     */
    private citedStepIdentifiers(data: ReportData): Set<string> {
        const identifiers = new Set<string>();

        for (const finding of data.analysis.analysis.findings) {
            for (const step of finding.evidence.steps) {
                identifiers.add(step.identifier);
            }
        }

        return identifiers;
    }

    /**
     * One transcript line per step.
     *
     * Layout: step-number  [cited]  "announcement text"  [</>]
     * Markup expands inline below the line, not in a sibling row.
     */
    private buildRow(
        step: {
            index: number;
            identifier: string;
            spokenPhrases: string[];
            itemText: string;
            htmlSnippet: string | null;
        },
        walk: string,
        cited: Set<string>
    ): string {
        const spoken = step.spokenPhrases.join(' ') || step.itemText || '(no announcement)';
        const isCited = cited.has(step.identifier);
        const markup = step.htmlSnippet ? this.formatHtmlSnippet(step.htmlSnippet) : null;
        const lineId = `step-${escapeHtml(step.identifier)}`;
        const markupId = `markup-${escapeHtml(step.identifier)}`;
        const walkAttr = escapeHtml(walk);

        const citedBadge = isCited
            ? `<span class="t-cited" title="Cited as evidence by the analysis">cited</span>`
            : '';

        const markupToggle = markup
            ? `<button type="button" class="t-markup-toggle" aria-expanded="false" aria-controls="${markupId}" title="Show HTML markup">&lt;/&gt;</button>`
            : '';

        const markupBlock = markup
            ? `<div class="t-markup" id="${markupId}" hidden><pre><code>${markup}</code></pre></div>`
            : '';

        return `<div class="t-line${isCited ? ' t-line--cited' : ''}" id="${lineId}" data-walk="${walkAttr}">
    <span class="t-num"><a href="#${lineId}" tabindex="-1" aria-label="Step ${step.index}">${step.index}</a></span>
    <span class="t-text">${escapeHtml(spoken)}</span>
    <span class="t-actions">${citedBadge}${markupToggle}</span>
    ${markupBlock}
</div>`;
    }

    /**
     * Format HTML snippet with proper indentation for readability.
     * Uses node-html-parser for reliable HTML parsing and formatting.
     */
    private formatHtmlSnippet(html: string): string {
        // Truncate if too long before formatting
        const snippet = html.length > 600 ? html.slice(0, 600) + '...' : html;

        try {
            // eslint-disable-next-line @typescript-eslint/no-var-requires
            const { parse } = require('node-html-parser');
            const root = parse(snippet, {
                lowerCaseTagName: false,
                comment: true,
                voidTag: {
                    tags: [
                        'area',
                        'base',
                        'br',
                        'col',
                        'embed',
                        'hr',
                        'img',
                        'input',
                        'link',
                        'meta',
                        'param',
                        'source',
                        'track',
                        'wbr',
                    ],
                },
            });

            // Format with indentation
            const formatted = this.formatNode(root, 0);
            return escapeHtml(formatted.trim());
        } catch {
            // Fallback to basic formatting if parser fails
            return escapeHtml(this.basicHtmlFormat(snippet));
        }
    }

    /**
     * Recursively format an HTML node with indentation.
     */
    private formatNode(node: any, depth: number): string {
        const indent = '  '.repeat(depth);

        // Text node
        if (node.nodeType === 3) {
            const text = node.text?.trim();
            return text ? `${indent}${text}\n` : '';
        }

        // Comment node
        if (node.nodeType === 8) {
            return `${indent}<!--${node.text}-->\n`;
        }

        // Root node - just process children
        if (!node.tagName) {
            return node.childNodes?.map((child: any) => this.formatNode(child, depth)).join('') || '';
        }

        // Element node
        const tagName = node.tagName.toLowerCase();
        const attrs = node.rawAttrs ? ` ${node.rawAttrs}` : '';

        // Void elements (self-closing)
        const voidTags = [
            'area',
            'base',
            'br',
            'col',
            'embed',
            'hr',
            'img',
            'input',
            'link',
            'meta',
            'param',
            'source',
            'track',
            'wbr',
        ];
        if (voidTags.includes(tagName)) {
            return `${indent}<${tagName}${attrs}>\n`;
        }

        // Get children content
        const children = node.childNodes || [];
        const hasOnlyText = children.length === 1 && children[0].nodeType === 3;
        const textContent = hasOnlyText ? children[0].text?.trim() : '';

        // Short inline elements - keep on one line
        if (hasOnlyText && textContent && textContent.length < 40) {
            return `${indent}<${tagName}${attrs}>${textContent}</${tagName}>\n`;
        }

        // Elements with children - format with newlines
        if (children.length > 0) {
            const childContent = children.map((child: any) => this.formatNode(child, depth + 1)).join('');
            return `${indent}<${tagName}${attrs}>\n${childContent}${indent}</${tagName}>\n`;
        }

        // Empty elements
        return `${indent}<${tagName}${attrs}></${tagName}>\n`;
    }

    /**
     * Basic HTML formatting fallback.
     */
    private basicHtmlFormat(html: string): string {
        let formatted = html.replace(/></g, '>\n<').replace(/\/>/g, '/>\n');

        const lines = formatted.split('\n');
        let indent = 0;
        const indentedLines: string[] = [];

        for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed) continue;

            if (trimmed.startsWith('</')) {
                indent = Math.max(0, indent - 1);
            }

            indentedLines.push('  '.repeat(indent) + trimmed);

            if (
                trimmed.startsWith('<') &&
                !trimmed.startsWith('</') &&
                !trimmed.startsWith('<!') &&
                !trimmed.endsWith('/>') &&
                !trimmed.includes('</')
            ) {
                indent++;
            }

            if (trimmed.includes('</') && !trimmed.startsWith('</')) {
                indent = Math.max(0, indent - 1);
            }
        }

        return indentedLines.join('\n');
    }

    // -------------------------------------------------------------------------
    // Styles
    // -------------------------------------------------------------------------

    private getStyles(opts: Required<HtmlReporterOptions>): string {
        return `
:root {
    --bg-primary: #ffffff;
    --bg-secondary: #f5f5f5;
    --text-primary: #212121;
    --text-secondary: #757575;
    --border-color: #e0e0e0;
    --accent-color: #1976d2;
    --success-color: #388e3c;
    --warning-color: #f57c00;
    --error-color: #d32f2f;
    --card-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

[data-theme="dark"] {
    --bg-primary: #121212;
    --bg-secondary: #1e1e1e;
    --text-primary: #e0e0e0;
    --text-secondary: #9e9e9e;
    --border-color: #333333;
    --card-shadow: 0 2px 4px rgba(0,0,0,0.3);
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

html {
    scroll-behavior: smooth;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    background-color: var(--bg-secondary);
    color: var(--text-primary);
    line-height: 1.6;
}

header {
    background: var(--accent-color);
    color: white;
    padding: 2rem;
    margin-bottom: 2rem;
}

.header-content {
    display: flex;
    align-items: center;
    gap: 1rem;
    max-width: 1200px;
    margin: 0 auto;
}

.header-content h1 {
    font-size: 1.75rem;
    font-weight: 600;
}

.page-info {
    margin-top: 0.5rem;
    font-size: 0.9rem;
    opacity: 0.9;
}

.page-info a {
    color: inherit;
}

.meta-info {
    display: flex;
    gap: 2rem;
    max-width: 1200px;
    margin: 1rem auto 0;
    font-size: 0.85rem;
    opacity: 0.8;
}

.logo {
    height: 48px;
    width: auto;
}

main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 1rem 2rem;
}

section {
    background: var(--bg-primary);
    border-radius: 8px;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
    box-shadow: var(--card-shadow);
}

h2 {
    font-size: 1.25rem;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid var(--border-color);
}

h3 {
    font-size: 1.1rem;
    margin: 1rem 0 0.75rem;
}

h4 {
    font-size: 0.9rem;
    color: var(--text-secondary);
    margin-bottom: 0.25rem;
}

.count {
    font-weight: normal;
    color: var(--text-secondary);
    font-size: 0.9em;
}

/* Summary */
.assessment-badge {
    display: inline-block;
    padding: 0.5rem 1rem;
    border-radius: 4px;
    font-weight: 600;
    font-size: 1.1rem;
    background-color: var(--badge-color);
    color: white;
    margin-bottom: 1rem;
}

.stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
    gap: 1rem;
    margin: 1rem 0;
}

.stat-card {
    text-align: center;
    padding: 1rem;
    background: var(--bg-secondary);
    border-radius: 8px;
}

.stat-value {
    display: block;
    font-size: 2rem;
    font-weight: 700;
    color: var(--accent-color);
}

.stat-label {
    font-size: 0.85rem;
    color: var(--text-secondary);
}

.major-concerns {
    margin-top: 1rem;
    padding: 1rem;
    background: #fff3e0;
    border-radius: 4px;
    border-left: 4px solid var(--warning-color);
}

[data-theme="dark"] .major-concerns {
    background: #3e2723;
}

.major-concerns h3 {
    margin-top: 0;
    color: var(--warning-color);
}

.major-concerns ul {
    margin-left: 1.5rem;
}

/* Cards */
.finding-card, .enhancement-card {
    background: var(--bg-secondary);
    border-radius: 8px;
    padding: 1rem;
    margin-bottom: 1rem;
    border-left: 4px solid var(--accent-color);
}

.finding-header, .enhancement-header {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin-bottom: 0.75rem;
}

.badge {
    display: inline-block;
    padding: 0.2rem 0.5rem;
    border-radius: 4px;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
}

.badge.confidence {
    background-color: var(--badge-color);
    color: white;
}

.badge.classification {
    background-color: var(--accent-color);
    color: white;
}

.badge.rule-link {
    background-color: var(--bg-primary);
    border: 1px solid var(--border-color);
}

.finding-issue {
    font-weight: 500;
    margin-bottom: 0.75rem;
}

.finding-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
    font-size: 0.85rem;
    color: var(--text-secondary);
    margin-bottom: 1rem;
    padding-bottom: 0.75rem;
    border-bottom: 1px solid var(--border-color);
}

.detail-section {
    margin-bottom: 0.75rem;
}

.evidence-list {
    margin-left: 1.5rem;
}

.evidence-list li {
    margin-bottom: 0.5rem;
}

.evidence-link {
    text-decoration: none;
    margin-right: 0.5rem;
}

.evidence-ref {
    display: inline-block;
    padding: 0.15rem 0.4rem;
    background: var(--accent-color);
    color: white;
    border-radius: 4px;
    font-size: 0.75rem;
    font-weight: 600;
    font-family: monospace;
}

.evidence-link:hover .evidence-ref {
    background: var(--text-primary);
}

.evidence-list code {
    background: var(--bg-primary);
    padding: 0.2rem 0.4rem;
    border-radius: 4px;
    font-size: 0.85rem;
}

.positions {
    font-size: 0.85rem;
    color: var(--text-secondary);
    margin-top: 0.5rem;
}

.human-review {
    font-size: 0.85rem;
    color: var(--warning-color);
    margin-top: 0.75rem;
}

.wcag-badge {
    background: var(--bg-primary);
    padding: 0.1rem 0.4rem;
    border-radius: 4px;
    font-size: 0.8rem;
    margin-left: 0.5rem;
}

.tool-badge {
    background: var(--bg-secondary);
    padding: 0.1rem 0.4rem;
    border-radius: 4px;
    font-size: 0.75rem;
    margin-left: 0.5rem;
    color: var(--text-secondary);
}

details {
    margin-top: 0.5rem;
}

summary {
    cursor: pointer;
    color: var(--accent-color);
    font-size: 0.85rem;
}

pre {
    background: var(--bg-primary);
    padding: 0.75rem;
    border-radius: 4px;
    overflow-x: auto;
    font-size: 0.8rem;
    margin-top: 0.5rem;
}

/* Debug details */
.debug-details {
    margin-top: 1rem;
    border-top: 1px solid var(--border-color);
    padding-top: 0.75rem;
}

.debug-details summary {
    cursor: pointer;
    font-size: 0.85rem;
    color: var(--text-secondary);
}

.debug-details summary:hover {
    color: var(--accent-color);
}

.debug-json {
    margin-top: 0.5rem;
    padding: 0.75rem;
    background: #f8f8f8;
    border-radius: 4px;
    font-size: 0.7rem;
    overflow-x: auto;
    max-height: 300px;
    overflow-y: auto;
}

[data-theme="dark"] .debug-json {
    background: #1a1a1a;
}

.debug-json code {
    color: var(--text-secondary);
}

/* Limitations */
.limitations {
    background: #e3f2fd;
    border-left: 4px solid var(--accent-color);
}

[data-theme="dark"] .limitations {
    background: #0d47a1;
}

.limitations ul {
    margin-left: 1.5rem;
}

/* Footer */
footer {
    text-align: center;
    padding: 2rem;
    color: var(--text-secondary);
    font-size: 0.85rem;
}

/* No items message */
.no-items {
    color: var(--text-secondary);
    font-style: italic;
}

/* Original violation in enhancement */
.original-violation-full {
    background: var(--bg-secondary);
    padding: 1rem;
    border-radius: 4px;
    margin-bottom: 1rem;
    border-left: 3px solid var(--accent-color);
}

.violation-meta {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.5rem;
}

.impact-badge {
    background: var(--bg-primary);
    padding: 0.1rem 0.4rem;
    border-radius: 4px;
    font-size: 0.75rem;
    color: var(--text-secondary);
}

.violation-message {
    margin: 0.5rem 0;
    font-size: 0.9rem;
}

.violation-selector {
    margin: 0.5rem 0;
    font-size: 0.8rem;
}

.violation-selector code {
    background: var(--bg-primary);
    padding: 0.2rem 0.4rem;
    border-radius: 4px;
}

.violation-html {
    margin: 0.5rem 0 0 0;
    padding: 0.5rem;
    background: var(--bg-primary);
    border-radius: 4px;
    font-size: 0.75rem;
    overflow-x: auto;
}

.violation-html code {
    color: var(--text-secondary);
}

.violation-id {
    font-size: 0.85rem;
}

/* Transcript */
.transcript {
    background: var(--bg-primary);
}

.visually-hidden {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: -1px;
    padding: 0;
    overflow: hidden;
    clip: rect(0 0 0 0);
    white-space: nowrap;
    border: 0;
}

/* Controls bar */
.t-controls {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    flex-wrap: wrap;
    margin-bottom: 1.25rem;
}

.t-search input {
    min-width: min(260px, 100%);
    padding: 0.4rem 0.65rem;
    font-size: 0.85rem;
    color: var(--text-primary);
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    border-radius: 5px;
    font-family: inherit;
}

.t-search input:focus-visible {
    outline: 2px solid var(--accent-color);
    outline-offset: 1px;
}

.t-chips {
    display: flex;
    gap: 0.3rem;
    flex-wrap: wrap;
}

.t-chip {
    display: inline-flex;
    align-items: center;
    gap: 0.35em;
    padding: 0.25rem 0.6rem;
    font-size: 0.78rem;
    font-family: inherit;
    color: var(--text-secondary);
    background: transparent;
    border: 1px solid var(--border-color);
    border-radius: 999px;
    cursor: pointer;
    white-space: nowrap;
}

.t-chip:hover {
    color: var(--text-primary);
    border-color: var(--text-secondary);
}

.t-chip:focus-visible {
    outline: 2px solid var(--accent-color);
    outline-offset: 1px;
}

.t-chip.is-active {
    color: var(--bg-primary);
    background: var(--text-primary);
    border-color: var(--text-primary);
}

.t-chip-count {
    opacity: 0.55;
    font-variant-numeric: tabular-nums;
    font-size: 0.9em;
}

.t-status {
    margin: 0;
    font-size: 0.82rem;
    color: var(--text-secondary);
    font-variant-numeric: tabular-nums;
}

/* Walk blocks */
.t-body {
    display: flex;
    flex-direction: column;
    gap: 0;
}

.t-walk-block {
    border-top: 1px solid var(--border-color);
}

.t-walk-block[hidden] {
    display: none;
}

.t-walk-header {
    display: flex;
    align-items: baseline;
    gap: 0.6rem;
    padding: 0.6rem 0;
    cursor: default;
}

.t-walk-name {
    font-size: 0.72rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: var(--text-secondary);
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
}

.t-walk-count {
    font-size: 0.72rem;
    color: var(--text-secondary);
    opacity: 0.6;
}

/* Transcript lines */
.t-lines {
    display: flex;
    flex-direction: column;
    padding-bottom: 0.5rem;
}

.t-line {
    display: grid;
    grid-template-columns: 3ch 1fr auto;
    grid-template-rows: auto auto;
    column-gap: 1rem;
    align-items: baseline;
    padding: 0.3rem 0;
    border-radius: 3px;
}

.t-line[hidden] {
    display: none;
}

.t-line:hover {
    background: var(--bg-secondary);
}

.t-line:target {
    background: var(--bg-secondary);
    outline: 1px solid var(--accent-color);
    outline-offset: 2px;
}

/* Cited lines get a left-gutter accent */
.t-line--cited {
    border-left: 2px solid var(--accent-color);
    padding-left: 0.5rem;
    margin-left: -0.5rem;
}

.t-num {
    grid-column: 1;
    grid-row: 1;
    text-align: right;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.72rem;
    color: var(--text-secondary);
    opacity: 0.5;
    user-select: none;
    padding-top: 0.05em;
}

.t-num a {
    color: inherit;
    text-decoration: none;
}

.t-num a:hover,
.t-num a:focus-visible {
    opacity: 1;
    color: var(--accent-color);
}

.t-text {
    grid-column: 2;
    grid-row: 1;
    font-size: 0.9rem;
    line-height: 1.55;
    color: var(--text-primary);
}

.t-actions {
    grid-column: 3;
    grid-row: 1;
    display: flex;
    align-items: center;
    gap: 0.35rem;
    white-space: nowrap;
}

.t-cited {
    font-size: 0.66rem;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--accent-color);
    border: 1px solid currentColor;
    border-radius: 999px;
    padding: 0.05rem 0.4rem;
    opacity: 0.8;
}

.t-markup-toggle {
    padding: 0.1rem 0.3rem;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.72rem;
    color: var(--text-secondary);
    background: transparent;
    border: 1px solid transparent;
    border-radius: 3px;
    cursor: pointer;
    opacity: 0.6;
}

.t-markup-toggle:hover {
    opacity: 1;
    border-color: var(--border-color);
}

.t-markup-toggle:focus-visible {
    outline: 2px solid var(--accent-color);
    outline-offset: 1px;
}

.t-markup-toggle[aria-expanded="true"] {
    opacity: 1;
    color: var(--accent-color);
    border-color: var(--border-color);
}

/* Inline markup block */
.t-markup {
    grid-column: 2 / 4;
    grid-row: 2;
    margin-top: 0.35rem;
    margin-bottom: 0.2rem;
}

.t-markup[hidden] {
    display: none;
}

.t-markup pre {
    margin: 0;
    padding: 0.6rem 0.8rem;
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    border-radius: 4px;
    font-size: 0.75rem;
    overflow-x: auto;
    line-height: 1.5;
}

.t-markup code {
    color: var(--text-secondary);
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
}


/* Responsive */
@media (max-width: 768px) {
    header {
        padding: 1rem;
    }
    
    .header-content {
        flex-direction: column;
        text-align: center;
    }
    
    .meta-info {
        flex-direction: column;
        gap: 0.5rem;
    }
    
    .stats-grid {
        grid-template-columns: repeat(2, 1fr);
    }
}

${opts.customCss}
`;
    }

    // -------------------------------------------------------------------------
    // Scripts
    // -------------------------------------------------------------------------

    private getScripts(): string {
        return `
<script>
(function () {
    var input = document.getElementById('transcript-filter');
    var status = document.querySelector('.t-status');
    var chips = Array.prototype.slice.call(document.querySelectorAll('.t-chip'));
    var lines = Array.prototype.slice.call(document.querySelectorAll('.t-line'));
    var blocks = Array.prototype.slice.call(document.querySelectorAll('.t-walk-block'));
    var walk = 'all';

    function apply() {
        var query = (input ? input.value : '').trim().toLowerCase();
        var shown = 0;

        lines.forEach(function (line) {
            var text = (line.querySelector('.t-text') || line).textContent.toLowerCase();
            var matchesWalk = walk === 'all' || line.getAttribute('data-walk') === walk;
            var matchesText = query === '' || text.indexOf(query) !== -1;
            var visible = matchesWalk && matchesText;
            line.hidden = !visible;
            if (visible) shown++;
        });

        // Hide entire walk blocks when every line inside them is hidden
        blocks.forEach(function (block) {
            var visibleLines = block.querySelectorAll('.t-line:not([hidden])');
            block.hidden = visibleLines.length === 0;
        });

        var filtering = query !== '' || walk !== 'all';
        if (status) {
            status.textContent = filtering ? shown + (shown === 1 ? ' step' : ' steps') : '';
        }
    }

    function selectWalk(name) {
        walk = name;
        chips.forEach(function (chip) {
            var on = chip.getAttribute('data-walk') === name;
            chip.classList.toggle('is-active', on);
            chip.setAttribute('aria-pressed', on ? 'true' : 'false');
        });
        apply();
    }

    if (input) input.addEventListener('input', apply);

    chips.forEach(function (chip) {
        chip.addEventListener('click', function () {
            selectWalk(chip.getAttribute('data-walk'));
        });
    });

    // Markup toggle: expand/collapse inline .t-markup block
    document.querySelectorAll('.t-markup-toggle').forEach(function (toggle) {
        toggle.addEventListener('click', function () {
            var expanded = toggle.getAttribute('aria-expanded') === 'true';
            toggle.setAttribute('aria-expanded', expanded ? 'false' : 'true');
            var markup = document.getElementById(toggle.getAttribute('aria-controls'));
            if (markup) markup.hidden = expanded;
        });
    });

    // Evidence links can point at a line that the current filter is hiding — reveal it
    function revealTarget() {
        if (!location.hash) return;
        var target = document.getElementById(location.hash.slice(1));
        if (!target || !target.classList.contains('t-line')) return;
        if (target.hidden) {
            if (input) input.value = '';
            selectWalk('all');
        }
        target.scrollIntoView({ block: 'center' });
    }

    window.addEventListener('hashchange', revealTarget);
    revealTarget();
})();
</script>`;
    }

    // -------------------------------------------------------------------------
    // Utilities
    // -------------------------------------------------------------------------

    private groupBy<T>(items: T[], keyFn: (item: T) => string): Record<string, T[]> {
        const result: Record<string, T[]> = {};
        for (const item of items) {
            const key = keyFn(item);
            if (!result[key]) {
                result[key] = [];
            }
            result[key].push(item);
        }
        return result;
    }
}

// =============================================================================
// Factory Function
// =============================================================================

/**
 * Create an HTML reporter instance.
 */
export function createHtmlReporter(): HtmlReporter {
    return new HtmlReporter();
}
